### ISSUE TITLE
data-loading problems

### ISSUE THREAD

**Issue by FATFATANT** [kevin-xuan/Graph-Flashback#2]
It seems that the **trans_loc_file** can not be loaded. The Console reports **EOFError: Ran out of input** at  train.py:66
```
with open(setting.trans_loc_file, 'rb') as f:  # 时间POI graph
    transition_graph = pickle.load(f)  # 在cpu上
```
Could you please lend me a help?

**Comment by kevin-xuan** [comment]
Hello, have you downloaded the corresponding files according to the provided link? The reason may be that the file you are trying to read is empty. Please check your download process carefully, thank you.

**Comment by FATFATANT** [comment]
Thanks, I re-downloaded the files and somehow it no longer reports the error.  It's so nice of you to reply me in such a short while. 
I hope it not troubles you too much to help me with another problem. I found that the datasets used in the `generate_triplet.py`  and `construct_graph` is missing, could you please tell me where can I find them?

**Comment by kevin-xuan** [comment]
In section Data Preparation, we provide a download link to the "flashback_data.zip", and you need to unzip the file to the specified directory.
