### ISSUE TITLE
Question about the social relations of users

### ISSUE THREAD

**Issue by nidohsp** [kevin-xuan/Graph-Flashback#3]
Dear authors:
   Thank you for sharing your excellent work. I wonder where is the file about the social relations of users? It seems like the check-in files of Gowalla and 4sq don't contain this information？

**Comment by kevin-xuan** [comment]
The data link is introduced in Section 6 "EXPERIMENTS" in the paper, you can download the corresponding user profile file.

**Comment by nidohsp** [comment]
Thank you
