### ISSUE TITLE
For training new dataset

### ISSUE THREAD

**Issue by bb67ao** [kevin-xuan/Graph-Flashback#5]
Could please make a readme if I want to train my dataset

**Comment by kevin-xuan** [comment]
Thanks for your interest in this research, I update the readme to guide training the model on your own datasets.

**Comment by bb67ao** [comment]
such a great author I have to say,this must be a strong baseline

**Comment by bb67ao** [comment]
> Thanks for your interest in this research, I update the readme to guide training the model on your own datasets.

Is there a more easier operation? The readme you updated is still a bit difficult for a novice, because I want to quickly test the effect on our dataset

**Comment by kevin-xuan** [comment]
OK, I just re-update the instructions for training your models on your own datasets, see section Training your dataset. Moreover, I upload the pure code of KGE model by [this repository](https://github.com/kevin-xuan/KGE) to training your model on new datasets, which cannot contain some files that are crucial for reproducing the original results in the research paper. See **point 3** of section "Data preparation" for details.
