### ISSUE TITLE
请问能一个--friendship数据集的示例吗

### ISSUE THREAD

**Issue by zyzhang11** [kevin-xuan/Graph-Flashback#6]

**Comment by kevin-xuan** [comment]
什么意思呢？frendship数据集已经放到data目录下了，而且我们只在构建知识图 ([KGE](https://github.com/kevin-xuan/Graph-Flashback/blob/main/KGE/generate_triplet.py#L251))用到了frendship文件，在训练Graph-Flashback时并没有再使用frendship了.
