### ISSUE TITLE
发现一个读取数据的小bug

### ISSUE THREAD

**Issue by Yukayo** [kevin-xuan/Graph-Flashback#7]
这是flashback源程序的bug，在读取数据时以4sq为例，如果最后一个用户的签到次数大于101次，由于循环会比if判断先结束，导致最后一个用户没有被计算上，4sq最后一个用户编号273324的有效签到次数是17014次，这个用户被省略了

**Comment by kevin-xuan** [comment]
你说的是对的，我没有在意dataloader这部分，没有发现这个bug。现在就是变相地删除了最后一个用户的所有东西，这些模型性能都是在默认没有最后一个用户的前提下进行评估的，大体上影响不大，方法的有效性能够得到验证。
